version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_biblioteca
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3309:3306'
